import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Nav from '@/components/ui/navbar/Nav'
import './globals.css'
import StoreProvider from '@/store/StoreProvider'

const inter = Poppins({ weight:'400',preload:false })

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Nav />
          {children}
        </body>
      </html>
    </StoreProvider>
  )
}
